"""Freeze the raw snapshot: row counts and SHA256 per raw file, written to docs/data_manifest.md.

Run once the scrape is finished: python -m src.collect.manifest
Also writes data/raw/manifest.csv (one line per file) so the hashes can be re-verified later.
"""
from __future__ import annotations

import csv
import gzip
import hashlib
import json
from datetime import datetime, timezone

from .common import RAW, ROOT


def sha256(path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> None:
    rows = []
    for p in sorted(RAW.rglob("*")):
        if not p.is_file() or p.name in ("manifest.csv", ".steamid_salt") or p.suffix == ".tmp":
            continue
        n = ""
        if p.name.endswith(".jsonl.gz"):
            with gzip.open(p, "rt", encoding="utf-8") as f:
                n = sum(1 for _ in f)
        rows.append({"path": p.relative_to(ROOT).as_posix(), "bytes": p.stat().st_size, "rows": n, "sha256": sha256(p)})
    with open(RAW / "manifest.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["path", "bytes", "rows", "sha256"])
        w.writeheader()
        w.writerows(rows)

    groups: dict[str, dict] = {}
    for r in rows:
        g = r["path"].split("/")[2]
        s = groups.setdefault(g, {"files": 0, "bytes": 0, "rows": 0})
        s["files"] += 1
        s["bytes"] += r["bytes"]
        s["rows"] += r["rows"] or 0
    done = [json.loads(p.read_text()) for p in (RAW / "reviews").glob("*.done.json")]
    unfinished = list((RAW / "reviews").glob("*.state.json"))
    manifest_hash = sha256(RAW / "manifest.csv")

    lines = [
        "# Raw data manifest", "",
        f"Frozen: {datetime.now(timezone.utc).isoformat(timespec='seconds')} UTC. Generated by `python -m src.collect.manifest`.",
        "Raw data is not committed. Per-file hashes are in `data/raw/manifest.csv`, whose own SHA256 is:", "",
        f"`{manifest_hash}`", "",
        "| Folder | Files | Size (MB) | Review rows |", "| --- | --- | --- | --- |",
    ]
    for g, s in sorted(groups.items()):
        lines.append(f"| {g} | {s['files']} | {s['bytes'] / 1e6:,.1f} | {s['rows']:,} |" if s["rows"] else
                     f"| {g} | {s['files']} | {s['bytes'] / 1e6:,.1f} | |")
    exp = sum((m["query_summary"] or {}).get("total_reviews", 0) for m in done)
    got = sum(m["n"] for m in done)
    stops: dict[str, int] = {}
    for m in done:
        stops[m["stop_reason"]] = stops.get(m["stop_reason"], 0) + 1
    full = [m for m in done if m["stop_reason"] != "capped"]
    capped = [m for m in done if m["stop_reason"] == "capped"]
    got_f = sum(m["n"] for m in full)
    exp_f = sum((m["query_summary"] or {}).get("total_reviews", 0) for m in full)
    lines += ["", "## Review scrape coverage", "",
              f"- Games finished: {len(done)}; unfinished: {len(unfinished)}",
              f"- Reviews collected: {got:,} vs Steam-reported total {exp:,} ({got / max(exp, 1):.1%} overall)",
              f"- Fully scraped games ({len(full)}): {got_f:,} of {exp_f:,} ({got_f / max(exp_f, 1):.2%}); the gap is "
              "reviews Steam counts but no longer returns (deleted/hidden)",
              f"- Capped games ({len(capped)}, newest ~15,000 reviews each): "
              + ", ".join(f"{m['appid']} ({m['n']:,} of {(m['query_summary'] or {}).get('total_reviews', 0):,})" for m in capped),
              f"- Stop reasons: {stops}",
              "- Rows may contain duplicate `recommendationid` after a crash/resume; dedupe in cleaning."]
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "data_manifest.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
